name: Deploy VitePress to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build VitePress
        run: npm run docs:build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.personal_token_on_actions }}
          publish_dir: /.vitepress/dist # Vitepress 构建输出的目录
          external_repository: wolff-h/wolff-h.github.io # 目标仓库
          keep_files: false